### PR TITLE
made the driver config variable get used

### PR DESCRIPTION
**Pull request by xLink**

### CODE REVIEW

**Comment by driesvints** [comment]
Heya! I gave some reasons at #41 why I don't want to do this. If you need to solve this right now, I suggest you overwrite the method and register your own Service Provider.

**Comment by driesvints** [comment]
If you want, you can give it a shot at implementing Laravel's manager so we can use the same system as Laravel's DB drivers.

**Comment by xLink** [comment]
ahhh i didnt see the reply in the issue, githubs notifications man bah... yeah ill override in my project, but in which case that config var is useless isnt it? :D

**Comment by driesvints** [comment]
You still need to say if you want the array or database driver

**Pull request closed without merging**
