### PR TITLE
update to L5.1

### PR DESCRIPTION
**Pull request by xLink**
this will update the components used
and bump the required php version to the same one L5.1 wants

tested this on my local app, doesn't seem to be any issues at the moment

### CODE REVIEW

**Comment by driesvints** [comment]
Is it possible to use a less strict version constraint? So people on L5.0 can still use the package? Try `^5`  as constraint for the Illuminate packages.

**Comment by driesvints** [comment]
The upgrade to `5.5.9` is ok for me but I'll have to remember to increment the minor version number for this :)

**Comment by xLink** [comment]
rejigged the illuminate requirements, retested locally, still works :D

**Comment by driesvints** [comment]
@xLink can you remove the PHP 5.4 test requirement from the travis file? The rest seems to be working :)

**Comment by xLink** [comment]
sweet looks to have fixed the tests in here too :D

**Comment by driesvints** [comment]
Thanks! :)

I'll try to tag a new release later this evening.

**Comment by xLink** [comment]
readme.md needs updating too xD

**Comment by driesvints** [comment]
I loved the min PHP version again so devs on 5.0 and are on a lower version can still use it for now. The 5.1 dependencies will require the min PHP version of 5.5.9 by themselves.

**Pull request merged**
