### PR TITLE
Updating service provider and readme to Laravel 5

### PR DESCRIPTION
**Pull request by stygiansabyss**
Now that Laravel 5 has documentation on package development, I have updated the service provider to reflect the new way this is done.

### CODE REVIEW

**Comment by stygiansabyss** [comment]
If you accept this PR, I might suggest putting it in a develop branch. This would also take care of issue #11

**Comment by besologic** [comment]
@stygiansabyss, I added your fork to my project, but `php artisan vendor:publish` doesn't seem to successfully publish the `lock-laravel.php` file on the most recent L5 release. Have you run into this before?

**Comment by besologic** [comment]
Boneheaded mistake on my part, didn't add it to the ServiceProviders array. :) 

I did run across an issue with the `register` method when I fixed my own error, I've initiated a PR on your repo with the fix.

**Comment by driesvints** [comment]
Hey there, I've decided to merge in @kirkbushell's PR for this: #17 

However, I still want to thank you for contributing! Thanks for helping out :)

And sorry it took so long to get this added!

**Pull request closed without merging**
