### PR TITLE
Laravel 5 support including bug fixes

### LINKED ISSUE #11: Use in Laravel 5?
I assume the answer is no, but is this package Laravel 5 ready yet? It installs fine, but on running `./artisan`:

```php
exception 'BadMethodCallException' with message 'Call to undefined method [package]' in ~\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php:168
Stack trace:
#0 ~\vendor\beatswitch\lock-laravel\src\LockServiceProvider.php(41): Illuminate\Support\ServiceProvider->__call('package', Array)
#1 ~\vendor\beatswitch\lock-laravel\src\LockServiceProvider.php(41): BeatSwitch\Lock\Integrations\Laravel\LockServiceProvider->package('beatswitch/lock...', 'lock-laravel', 'E:\\Files\\Docume...')
#2 ~\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(393): BeatSwitch\Lock\Integrations\Laravel\LockServiceProvider->register()
#3 ~\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(514): Illuminate\Foundation\Application->register(Object(BeatSwitch\Lock\Integrations\Laravel\LockServiceProvider))
#4 ~\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(496): Illuminate\Foundation\Application->registerDeferredProvider('BeatSwitch\\Lock...', 'lock')
#5 ~\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(470): Illuminate\Foundation\Application->loadDeferredProvider('lock')
#6 ~\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(183): Illuminate\Foundation\Application->loadDeferredProviders()
#7 ~\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(89): Illuminate\Foundation\Console\Kernel->bootstrap()
#8 ~\artisan(34): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}
```

Any ideas?

### PR DESCRIPTION
**Pull request by kirkbushell**
Also included is a little test refactoring.

Fixes #11.

### CODE REVIEW

**Comment by barryvdh** [comment]
I don't think L5 is following SemVer, so you might be better of using 5.0.x for now (if you haven't tagged yet)

**Comment by driesvints** [comment]
@barryvdh hmm, I don't know. I doubt that there will be breaking changes in upcoming 5.x releases for the stuff we use.

**Comment by barryvdh** [comment]
Well probably not indeed, but you don't know that until 5.1 (or 5.2 or 5.9?) is released.

**Comment by kirkbushell** [comment]
@barryvdh one of the reasons for the L5 move to version 5, rather than 4.3 - was semver.

**Comment by barryvdh** [comment]
Yeah I thought so but according to @GrahamCampbell that's not the case.

**Comment by barryvdh** [comment]
I'll ask Taylor what he thinks ;) https://twitter.com/barryvdh/status/574922812533686272

**Comment by barryvdh** [comment]
So answer from Taylor:
https://twitter.com/taylorotwell/status/574942568619757568
> I would use 5.0.x… not that anything major will change, but sometimes very small thing sdo

So you with that what you like ;) It's just easier to add 5.1 support later than remove it once a release has been tagged.

But a release is tagged already anyways, so it's a bit pointless now ;)

**Comment by kirkbushell** [comment]
Right, yeah - so not true semver.

**Comment by driesvints** [comment]
K, I'll try to add a better constraint later.

**Comment by kirkbushell** [comment]
@driesvints already on it buddy :)

**Comment by driesvints** [comment]
I'm changing it again back to `^5`. Just gives more flexibility for people to choose the version with what they're gonna work with.

**Comment by GrahamCampbell** [comment]
> I'm changing it again back to ^5. Just gives more flexibility for people to choose the version with what they're gonna work with.

Bad idea.

**Comment by GrahamCampbell** [comment]
That means you're saying it's compatible with laravel 5.4, even if it's not. Changing the version constraint back at a later time isn't good enough - it's too late by then.

**Comment by driesvints** [comment]
@GrahamCampbell the version constraint was at `5.0.*` before the new release was tagged (just now). Now that it's at `^5` both people on L5 and L5.1 can use the package.

Why wouldn't it be compatible? Because Laravel isn't following SemVer? I could also require the current version to be L5.1 only but that would mean for L5 apps that they're stuck.

**Comment by driesvints** [comment]
What about `>=5.0,<5.2`?

**Comment by barryvdh** [comment]
That would be safer indeed. Or '5.0.x|5.1.x', same effect.
if 5.2 doesn't change much you can just loosen it in 6 months or so :)

**Comment by driesvints** [comment]
@barryvdh ok thanks. I'll update it :)

**Comment by GrahamCampbell** [comment]
> Now that it's at ^5 both people on L5 and L5.1 can use the package.

That's not what that means though. It means all 5.x.

> if 5.2 doesn't change much you can just loosen it in 6 months or so :)

No you can't, because that will still lead you to the same problems.

> @barryvdh ok thanks. I'll update it :)

If you've already tagged a release with these bad version constraints, and further changes are totally pointless because you've already made a mess.

**Comment by barryvdh** [comment]
Oh didn't see it was tagged already. But yeah, then it doesn't help much, because someone with Laravel 5.9 will still get 0.3.0 instead of an error.
But it's an 0.x release, so probably not the end of the world ;)

**Comment by GrahamCampbell** [comment]
As long as we recommend `^0.3.1` as a version constraint, this issue can be avoided(ish).

**Comment by barryvdh** [comment]
Or just make sure you update to new Laravel version on time ;)

**Comment by driesvints** [comment]
And what if I push a `0.3.1` tag and purge the tag on github and the release on packagist? That way nobody can get it anymore.

**Comment by GrahamCampbell** [comment]
> And what if I push a 0.3.1 tag and purge the 0.3.0 tag on github and the release on packagist? That way nobody can get it anymore.

Best of retagging 0.3.0 if you're going to do that.

**Comment by GrahamCampbell** [comment]
Because composer will still be cashing the 0.3.0 release even after you delete it. :/

**Comment by driesvints** [comment]
> Because composer will still be cashing the 0.3.0 release even after you delete it. :/

Ah k, didn't know that. Thanks for letting me know.

This has all happened within a really short period of time btw (~2 hours) I doubt much people have updated already.

**Comment by GrahamCampbell** [comment]
Hopefully. :)

**Comment by driesvints** [comment]
Ok. Should be all good now. Thanks for the help guys :)

**Pull request merged**
