### PR TITLE
included L5.5

### PR DESCRIPTION
**Pull request by xLink**
Hey! Ran some tests, this seems to work with L5.5.14 without issues.
:D

### CODE REVIEW

**Comment by xLink** [comment]
@driesvints  ping ^^

**Comment by driesvints** [comment]
Thanks!

**Comment by driesvints** [comment]
@xLink btw, you may want to link your email address to your Github account so your commits have proper authorship.

**Comment by xLink** [comment]
@driesvints ahhh its from my work address thats why :>, thanks for merging!

**Pull request merged**
